/* eslint-disable jsx-a11y/alt-text */
/* eslint-disable @next/next/no-img-element */
/* eslint-disable react/jsx-no-comment-textnodes */
import Head from 'next/head';
import Header from '@/components/header';
import React from 'react';
import styles from '../styles/home.module.css';
import 'react-responsive-carousel/lib/styles/carousel.min.css';
import { Carousel } from 'react-responsive-carousel';
import Link from 'next/link';
import MovieList from '@/components/movielist';
import { useEffect, useState } from 'react';

export default function Home() {
  const [popularMovies, setPopularMovies] = useState([]);

  useEffect(() => {
    fetch(
      'https://api.themoviedb.org/3/movie/popular?api_key=4e44d9029b1270a757cddc766a1bcb63&language=en-US'
    )
      .then((res) => res.json())
      .then((data) => setPopularMovies(data.results));
  }, []);

  // console.log(popularMovies)

  return (
    <div className="min-h-screen bg-black overflow-hidden">
      <Head>
        <title>Movie App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <div className="poster">
        <Carousel
          showThumbs={false}
          autoPlay={true}
          transitionTime={3}
          infiniteLoop={true}
          showStatus={false}
        >
      
          {popularMovies.map((movie) => {
            // eslint-disable-next-line react/jsx-key
            return (
              <Link
                style={{ textDecoration: 'none', color: 'white' }}
                href={`/movie/${movie.id}`}
                key={movie.id}
              >

                <div className={styles.posterImage}>
                  <img
                    src={`https://image.tmdb.org/t/p/original${
                      movie && movie.backdrop_path
                    }`}
                    alt="Movie_poster"
                  />
                </div>
                <div className={styles.posterImage__overlay}>
                  <div className={styles.posterImage__title}>
                    {movie ? movie.original_title : ''}
                  </div>
                  <div className={styles.posterImage__runtime}>
                    {movie ? movie.release_date : ''}
                    <span className={styles.posterImage__rating}>
                      {movie ? movie.vote_average : ''}
                      <i className="fas fa-star" />{' '}
                    </span>
                  </div>
                  <div className={styles.posterImage__description}>
                    {movie ? movie.overview : ''}
                  </div>
                </div>
              </Link>
            );
          })}
        </Carousel>
        <MovieList />
      </div>
    </div>
  );
}
